/* SPDX-License-Identifier: GPL-2.0-only */

#ifndef _MSM_PANEL_PROP_H_
#define _MSM_PANEL_PROP_H_

#define DSI_PANEL_SAMSUNG_S6E3HC2 0
#define DSI_PANEL_SAMSUNG_S6E3FC2X01 1
#define DSI_PANEL_SAMSUNG_SOFEF03F_M 2
#define DSI_PANEL_SAMSUNG_ANA6705 3
#define DSI_PANEL_SAMSUNG_ANA6706 4
#define DSI_PANEL_SAMSUNG_AMB655XL 5
#define DSI_PANEL_SAMSUNG_AMB655XL08 6
#define DSI_PANEL_SAMSUNG_AMB670YF01 7
#define DSI_PANEL_SAMSUNG_SOFEF00_M 8

extern int dsi_panel_name;

#endif /* _MSM_PANEL_PROP_H_ */

