obj-$(CONFIG_PROJECT_INFO)   += project_info.o
obj-$(CONFIG_OEM_ABOARD)   += oem_aboard.o
obj-$(CONFIG_OEM_BOOT_MODE) += boot_mode.o
obj-$(CONFIG_RF_CABLE_DETECT) += op_rf_cable_monitor.o
obj-$(CONFIG_PSTORE_DEVICE_INFO) += device_info.o
obj-$(CONFIG_GPIO_SWITCH)  += gpio_switch.o
obj-$(CONFIG_OP_CMDLINE)  += op_cmdline.o
obj-$(CONFIG_SIM_HOLDER_DETECT) += sim_holder_detect.o
